"use client";
import { useState } from "react";
import { Copy, KeyRound, LoaderCircle, ShieldAlert } from "lucide-react";

type Key = { id: string; label: string; key_prefix: string; created_at: string; last_used_at: string | null; revoked_at: string | null };
export function GeobotKeyManager({ initialKeys, editable }: { initialKeys: Key[]; editable: boolean }) {
  const [keys, setKeys] = useState(initialKeys), [label, setLabel] = useState("Geobot produção"), [generated, setGenerated] = useState<string | null>(null), [busy, setBusy] = useState(false), [error, setError] = useState<string | null>(null);
  const generate = async () => { setBusy(true); setError(null); const response = await fetch("/api/admin/integracoes/geobot/keys", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ label }), cache: "no-store" }); const payload = await response.json(); setBusy(false); if (!response.ok) return setError("Não foi possível gerar a chave."); setGenerated(payload.data.key); setKeys((current) => [payload.data, ...current]); };
  const revoke = async (id: string) => { if (!window.confirm("Revogar esta chave? A Geobot deixará de conseguir usá-la imediatamente.")) return; setBusy(true); setError(null); const response = await fetch(`/api/admin/integracoes/geobot/keys?id=${encodeURIComponent(id)}`, { method: "DELETE" }); setBusy(false); if (!response.ok) return setError("Não foi possível revogar a chave."); setKeys((current) => current.map((key) => key.id === id ? { ...key, revoked_at: new Date().toISOString() } : key)); };
  return <section className="settings-card"><div className="settings-card-head"><div className="metric-icon"><KeyRound /></div><div><h2>API keys da Geobot</h2><p>As chaves são exibidas uma única vez, armazenadas somente como hash e podem ser revogadas.</p></div></div>{generated && <div className="success-banner"><ShieldAlert /><div><strong>Copie agora a nova API key</strong><code>{generated}</code><span>Ela não será mostrada novamente.</span></div><button type="button" className="btn btn-secondary" onClick={() => navigator.clipboard.writeText(generated)}><Copy /> Copiar</button></div>}{editable && <div className="setting-grid"><label className="setting-field"><span>Nome da chave</span><input value={label} maxLength={80} onChange={(event) => setLabel(event.target.value)} /></label><button type="button" className="btn" disabled={busy} onClick={generate}>{busy ? <LoaderCircle className="spin" /> : <KeyRound />} Gerar API key</button></div>}{error && <p className="form-error">{error}</p>}<div className="rank-list">{keys.length ? keys.map((key) => <div key={key.id}><span><KeyRound size={16} /></span><div><strong>{key.label}</strong><small>{key.key_prefix}… · criada em {new Date(key.created_at).toLocaleString("pt-BR")}{key.last_used_at ? ` · usada em ${new Date(key.last_used_at).toLocaleString("pt-BR")}` : ""}</small></div>{key.revoked_at ? <b>Revogada</b> : editable ? <button type="button" className="btn btn-secondary" disabled={busy} onClick={() => revoke(key.id)}>Revogar</button> : <b>Ativa</b>}</div>) : <div><span>—</span><div><strong>Nenhuma API key gerada</strong><small>Gere a primeira chave para conectar a Geobot.</small></div></div>}</div></section>;
}
