import { Activity, AlertTriangle, Clock3, Link2, XCircle } from "lucide-react";
import { getAdminSession } from "@/lib/auth";
import { getServiceClient } from "@/lib/supabase/server";
import { getGeobotEnvConfig } from "@/lib/integrations/config";
import { GeobotKeyManager } from "./key-manager";
import { saveGeobotIntegrationSettingsAction } from "./actions";

export const dynamic = "force-dynamic";

export default async function GeobotIntegrationPage({ searchParams }: { searchParams: Promise<{ salvo?: string; erro?: string }> }) {
  const params = await searchParams;
  const session = await getAdminSession(), db = getServiceClient(), env = getGeobotEnvConfig(), today = new Date().toISOString().slice(0, 10);
  const [settingsResult, eventsResult, linksResult, keysResult] = db ? await Promise.all([
    db.from("app_settings").select("key,value").like("key", "integrations.geobot.%"),
    db.from("integration_api_events").select("status_code,duration_ms,action,created_at").eq("integration_source", "geobot").gte("created_at", `${today}T00:00:00Z`).order("created_at", { ascending: false }).limit(250),
    db.from("short_links").select("id").eq("integration_source", "geobot").limit(250),
    db.from("integration_api_keys").select("id,label,key_prefix,created_at,last_used_at,revoked_at").eq("integration_source", "geobot").order("created_at", { ascending: false }),
  ]) : [{ data: [] }, { data: [] }, { data: [] }, { data: [] }];
  const settings = new Map((settingsResult.data ?? []).map((item) => [item.key, item.value]));
  const events = eventsResult.data ?? [], completed = events.filter((event) => event.status_code > 0), failures = completed.filter((event) => event.status_code >= 400), created = events.filter((event) => event.action === "link_created").length, average = completed.length ? Math.round(completed.reduce((sum, event) => sum + (event.duration_ms ?? 0), 0) / completed.length) : 0, editable = session?.role === "super_admin", databaseEnabled = Boolean(settings.get("integrations.geobot.enabled")), creationEnabled = Boolean(settings.get("integrations.geobot.creation_enabled")), keys = keysResult.data ?? [];
  return <main className="admin-main"><div className="admin-page-head"><div><span className="breadcrumb">Início / Integrações / Geobot</span><h1>Integração Geobot</h1><p>Métricas, saúde operacional e credenciais da API privada.</p></div><span className={`status ${env.enabled && databaseEnabled && creationEnabled ? "status-active" : "status-expired"}`}><i />{env.enabled && databaseEnabled && creationEnabled ? "Ativa" : "Pendente"}</span></div>{params.salvo && <div className="success-banner"><ShieldCheckIcon /> <div><strong>Integração atualizada</strong><span>O novo estado foi registrado na auditoria.</span></div></div>}{params.erro && <p className="form-error">{params.erro}</p>}<section className="metric-grid"><Metric icon={<Activity />} label="Solicitações hoje" value={events.filter((event) => event.action === "request_received").length} /><Metric icon={<Link2 />} label="Links criados" value={created} /><Metric icon={<Clock3 />} label="Duração média" value={`${average} ms`} /><Metric icon={<XCircle />} label="Taxa de erro" value={`${completed.length ? Math.round((failures.length / completed.length) * 100) : 0}%`} /></section><div className="dashboard-grid"><section className="admin-card"><div className="card-head"><div><h2>Saúde da integração</h2><p>Os valores das chaves nunca são exibidos.</p></div></div><div className="health-list"><Health label="Flag do ambiente" ok={env.enabled} /><Health label="Integração no banco" ok={databaseEnabled} /><Health label="Criação pela API" ok={creationEnabled} /><Health label="API key ativa" ok={keys.some((key) => !key.revoked_at) || Boolean(env.apiKey)} /><Health label="Última chamada" ok={events.length > 0} text={events[0] ? new Date(events[0].created_at).toLocaleString("pt-BR") : "Nenhuma"} /></div></section><section className="admin-card"><div className="card-head"><div><h2>Links originados pela Geobot</h2><p>Links ativos registrados pela integração.</p></div></div><div className="metric-card"><div className="metric-icon"><Link2 /></div><span>Total consultado</span><strong>{linksResult.data?.length ?? 0}</strong></div></section></div>{editable && <form className="settings-content" action={saveGeobotIntegrationSettingsAction}><section className="settings-card"><div className="settings-card-head"><div className="metric-icon"><Activity /></div><div><h2>Controles administrativos</h2><p>A flag do ambiente também deve estar ativa no Vercel.</p></div></div><Switch name="enabled" label="Integração habilitada" checked={databaseEnabled} /><Switch name="creation" label="Criação de links habilitada" checked={creationEnabled} /><button className="btn">Salvar controles</button></section></form>}<GeobotKeyManager initialKeys={keys} editable={editable} /><section className="impact-note"><AlertTriangle /><span>Após gerar uma chave, cadastre o mesmo valor no painel administrativo da Geobot. A chave anterior pode permanecer ativa durante a troca e ser revogada somente após a validação.</span></section></main>;
}
function Metric({ icon, label, value }: { icon: React.ReactNode; label: string; value: string | number }) { return <article className="metric-card"><div className="metric-icon">{icon}</div><span>{label}</span><strong>{value}</strong></article>; }
function Health({ label, ok, text }: { label: string; ok: boolean; text?: string }) { return <span><i className={ok ? "ok" : "warn"} /><b>{label}</b><em>{text ?? (ok ? "Configurado" : "Pendente")}</em></span>; }
function Switch({ name, label, checked }: { name: string; label: string; checked: boolean }) { return <label className="setting-row"><div><span>{label}</span><small>integrations.geobot.{name === "creation" ? "creation_enabled" : "enabled"}</small></div><input className="switch" type="checkbox" name={name} defaultChecked={checked} /></label>; }
function ShieldCheckIcon() { return <span aria-hidden="true">✓</span>; }
