export const privacySections=[
{id:"introducao",title:"Introdução e operação",content:<><p>Esta Política explica como o Encurta.io trata dados ao oferecer links curtos autorizados. A plataforma é operada pela equipe responsável pelo Encurta.io, inicialmente em integração com a Alcance IA.</p></>},
{id:"dados",title:"Dados coletados",content:<><p>Podemos tratar nome, e-mail, conta administrativa, informações de autenticação, links cadastrados, destino, slug, status, datas, expiração e observações internas.</p><p>Em acessos, podemos registrar contagem de cliques, navegador, tipo de dispositivo, domínio de referência, país aproximado, identificação de bot e identificadores anonimizados.</p></>},
{id:"integracao-alcance",title:"Integração com a Alcance IA",content:<><p>Quando um link de WhatsApp é solicitado pelo backend da Alcance IA, podemos receber telefone, mensagem opcional, expiração e identificadores técnicos limitados. Esses dados são usados somente para validar e gerar o destino autorizado, garantir idempotência, segurança e auditoria.</p><p>A mensagem permanece no destino do link, sem cópia adicional em campos analíticos. Credenciais, assinaturas e corpos completos não são registrados. Registros técnicos de idempotência possuem retenção operacional limitada.</p></>},
{id:"administracao",title:"Dados administrativos",content:<><p>Atividades administrativas podem gerar registros de criação, alteração, bloqueio, exclusão lógica, autenticação e falhas de autorização. Denúncias podem conter o link informado, motivo, descrição e contato opcional.</p></>},
{id:"nao-coletamos",title:"O que não coletamos",content:<><p>O Encurta.io não solicita senha do WhatsApp, conteúdo de conversas, mensagens efetivamente enviadas, lista de contatos ou credenciais de serviços de terceiros. IP integral não deve ser mantido por tempo indeterminado.</p></>},
{id:"finalidades",title:"Finalidades e bases legais",content:<><p>Os dados são usados para prestar o serviço, autenticar administradores, gerar redirecionamentos, medir desempenho, prevenir abuso, investigar denúncias, manter segurança e cumprir obrigações legais. O tratamento pode se apoiar na execução do serviço, legítimo interesse, consentimento quando aplicável e cumprimento de obrigação legal.</p></>},
{id:"cookies",title:"Cookies e analytics",content:<><p>Cookies essenciais mantêm sessões administrativas. As métricas são agregadas e podem diferenciar acessos humanos, bots e dispositivos. Não usamos os links para acompanhar permanentemente pessoas entre serviços.</p></>},
{id:"compartilhamento",title:"Compartilhamento e fornecedores",content:<><p>Dados podem ser processados por fornecedores de infraestrutura, como hospedagem, banco de dados e autenticação, limitados às finalidades necessárias. Também podem ser compartilhados mediante obrigação legal ou investigação legítima.</p></>},
{id:"armazenamento",title:"Armazenamento e retenção",content:<><p>Os registros são armazenados pelo período necessário à operação, segurança, auditoria e cumprimento de obrigações. Eventos detalhados podem ter retenção menor que métricas agregadas. Exclusões administrativas usam remoção lógica quando a auditoria precisa ser preservada.</p></>},
{id:"seguranca",title:"Segurança",content:<><p>Adotamos controles de acesso, validação de destinos, registros de auditoria, hash de identificadores e restrição de segredos ao servidor. Nenhuma medida elimina integralmente todos os riscos.</p></>},
{id:"direitos",title:"Direitos do titular",content:<><p>Conforme a legislação aplicável, titulares podem solicitar confirmação, acesso, correção, informação sobre compartilhamento, oposição, portabilidade ou exclusão quando cabível. Algumas informações podem ser preservadas por obrigação legal, prevenção a fraude ou defesa de direitos.</p></>},
{id:"externos-menores",title:"Links externos e menores",content:<><p>O redirecionamento leva a serviços externos, sujeitos às próprias políticas. O serviço não é direcionado intencionalmente a crianças e adolescentes sem representação adequada.</p></>},
{id:"alteracoes",title:"Alterações e contato",content:<><p>Esta política pode ser atualizada para refletir mudanças operacionais ou legais. A data no topo identifica a versão vigente. Para dúvidas ou solicitações, utilize a página de denúncia e contato.</p></>},
];

export const acceptableSections=[
{id:"objetivo",title:"Objetivo e abrangência",content:<><p>Esta política estabelece o uso permitido do Encurta.io e se aplica a administradores, integrações autorizadas e qualquer pessoa que interaja com links da plataforma.</p></>},
{id:"permitido",title:"Uso permitido",content:<><p>É permitido criar links autorizados para comunicação legítima via WhatsApp, atendimento, orçamento e contato, respeitando a legislação, o consentimento dos destinatários e os direitos de terceiros.</p></>},
{id:"fraude",title:"Fraude, phishing e engenharia social",content:<><p>É proibido usar links para golpes, phishing, roubo de credenciais, engenharia social, impersonação, campanhas enganosas ou ocultação de destino malicioso.</p></>},
{id:"spam",title:"Spam e automação abusiva",content:<><p>Não é permitido distribuir spam, automatizar criação em massa, manipular tráfego, enumerar links, contornar limites, evadir bloqueios ou sobrecarregar deliberadamente a plataforma.</p></>},
{id:"conteudo",title:"Malware e conteúdo ilegal",content:<><p>São proibidos malware, perseguição, conteúdo ilegal, violações de marca ou direitos autorais, ameaças e materiais que facilitem atividades ilícitas.</p></>},
{id:"seguranca",title:"Segurança da plataforma",content:<><p>Tentativas de invadir o painel, explorar falhas, obter acesso não autorizado, interferir na autenticação ou testar credenciais sem autorização são proibidas.</p></>},
{id:"denuncias",title:"Denúncias e investigação",content:<><p>Denúncias são analisadas com base nas informações disponíveis. Podemos preservar registros, investigar atividades e solicitar contexto adicional sem tornar as denúncias públicas.</p></>},
{id:"medidas",title:"Bloqueio, remoção e reincidência",content:<><p>O Encurta.io poderá bloquear, desativar, remover ou suspender links e contas, inclusive preventivamente quando houver risco. Reincidência e gravidade podem influenciar as medidas adotadas.</p></>},
{id:"autoridades",title:"Cooperação e alterações",content:<><p>Podemos cooperar com autoridades competentes quando legalmente exigido. Esta política pode mudar para acompanhar riscos, tecnologia e legislação.</p></>},
{id:"contato",title:"Como denunciar",content:<><p>Use a página “Denunciar link” e informe o endereço, o motivo e uma descrição objetiva. Não envie senhas ou dados desnecessários.</p></>},
];

export const termsSections=[
{id:"aceitacao",title:"Aceitação e serviço",content:<><p>Ao utilizar o Encurta.io, você concorda com estes Termos. O serviço cria, gerencia e resolve links curtos para destinos autorizados, inicialmente links oficiais do WhatsApp.</p></>},
{id:"elegibilidade",title:"Elegibilidade e contas",content:<><p>O painel é restrito a usuários autorizados. O titular da conta deve manter suas credenciais seguras, informar incidentes e responder pelas atividades realizadas em sua sessão.</p></>},
{id:"criacao",title:"Criação e destinos permitidos",content:<><p>Links são criados administrativamente a partir de telefone e mensagem opcional. O Encurta.io pode alterar a lista de destinos permitidos para preservar segurança e operação.</p></>},
{id:"responsabilidade",title:"Responsabilidade do usuário",content:<><p>O usuário é responsável pela legitimidade do destino, conteúdo, consentimento e forma de divulgação. O link curto não transfere ao Encurta.io a responsabilidade pelo conteúdo de terceiros.</p></>},
{id:"disponibilidade",title:"Disponibilidade e redirecionamentos",content:<><p>Buscamos uma operação estável, mas o serviço pode sofrer interrupções, manutenção ou falhas. Redirecionamentos são temporários e podem deixar de funcionar quando o link expira, é desativado ou bloqueado.</p></>},
{id:"metricas",title:"Métricas",content:<><p>Contagens são estimativas operacionais. Bots, pré-visualizações de redes sociais, bloqueadores e falhas de rede podem afetar os números. Não garantimos tráfego, contatos, vendas ou resultados comerciais.</p></>},
{id:"propriedade",title:"Propriedade intelectual",content:<><p>A marca, interface e tecnologia do Encurta.io pertencem aos respectivos titulares. O uso do serviço não concede direito de copiar, revender ou explorar seus elementos fora destes Termos.</p></>},
{id:"privacidade",title:"Privacidade",content:<><p>O tratamento de dados segue a Política de Privacidade. O uso também está sujeito à Política de Uso Aceitável.</p></>},
{id:"proibicoes",title:"Usos proibidos e denúncias",content:<><p>Fraude, spam, phishing, invasão, evasão de limites e demais condutas descritas na Política de Uso Aceitável podem resultar em investigação e medidas imediatas.</p></>},
{id:"suspensao",title:"Suspensão e encerramento",content:<><p>Podemos suspender contas, bloquear links ou encerrar acesso quando necessário à segurança, cumprimento legal ou proteção de terceiros. Registros podem ser preservados quando houver fundamento legítimo.</p></>},
{id:"limitacoes",title:"Limitações e ausência de garantias",content:<><p>O serviço é oferecido conforme disponibilidade, sem garantias absolutas de continuidade, compatibilidade ou resultado. Limitações de responsabilidade serão aplicadas na extensão permitida pela legislação.</p></>},
{id:"legislacao",title:"Alterações, legislação e contato",content:<><p>Os Termos podem ser atualizados. A legislação brasileira rege a relação na medida aplicável. Dúvidas e denúncias podem ser enviadas pela página de contato.</p></>},
];
