import Link from "next/link";
import { ArrowRight, ExternalLink, Link2, Menu, ShieldCheck } from "lucide-react";

export function Brand(){return <Link className="brand" href="/" aria-label="Encurta.io — página inicial"><span className="brand-mark"><Link2 size={19}/></span><span>Encurta<span className="brand-dot">.io</span></span></Link>}

export function PublicHeader(){return <header className="site-header"><div className="site-container header-inner"><Brand/><nav className="desktop-nav" aria-label="Navegação principal"><Link href="/">Home</Link><Link href="/#como-funciona">Como funciona</Link><Link href="/#seguranca">Segurança</Link><Link href="/privacidade">Privacidade</Link><Link href="/termos">Termos</Link></nav><Link className="btn btn-sm" href="/login">Entrar <ArrowRight size={16}/></Link><details className="mobile-menu"><summary aria-label="Abrir menu"><Menu size={22}/></summary><nav aria-label="Navegação móvel"><Link href="/">Home</Link><Link href="/#como-funciona">Como funciona</Link><Link href="/#seguranca">Segurança</Link><Link href="/privacidade">Privacidade</Link><Link href="/termos">Termos</Link><Link href="/login">Entrar</Link></nav></details></div></header>}

export function PublicFooter(){return <footer className="site-footer"><div className="site-container footer-grid"><div><Brand/><p className="footer-intro">Links autorizados, redirecionamentos validados e controle centralizado.</p><div className="service-status"><span/> Serviço em operação</div></div><div><h3>Produto</h3><Link href="/">Home</Link><Link href="/#como-funciona">Como funciona</Link><Link href="/#seguranca">Segurança</Link></div><div><h3>Institucional</h3><Link href="/privacidade">Privacidade</Link><Link href="/termos">Termos</Link><Link href="/uso-aceitavel">Uso aceitável</Link><Link href="/denunciar">Denunciar link</Link></div><div><h3>Plataforma relacionada</h3><a href={process.env.NEXT_PUBLIC_ALCANCE_IA_URL??"https://alcance.ia.br"} target="_blank" rel="noreferrer">Alcance IA <ExternalLink size={13}/></a><p className="footer-trust"><ShieldCheck size={17}/> Destinos autorizados e monitorados</p></div></div><div className="site-container footer-bottom"><span>© {new Date().getFullYear()} Encurta.io</span><span>Construído para compartilhar com confiança.</span></div></footer>}

export function PublicShell({children}:{children:React.ReactNode}){return <><PublicHeader/><main>{children}</main><PublicFooter/></>}
