"use server";
import { headers } from "next/headers";
import { redirect } from "next/navigation";
import { z } from "zod";
import { getShortDomain } from "@/lib/config";
import { hashVisitorIdentifier } from "@/lib/analytics";
import { getServiceClient } from "@/lib/supabase/server";
const attempts=new Map<string,{count:number;reset:number}>();
const reportSchema=z.object({url:z.url(),reason:z.enum(["phishing","fraude","spam","malware","impersonacao","ilegal","direitos","outro"]),description:z.string().min(20).max(2000),name:z.string().max(120).optional(),email:z.union([z.email(),z.literal("")]).optional(),evidence:z.string().max(1500).optional(),goodFaith:z.literal("on"),privacy:z.literal("on"),website:z.string().max(0)});
export async function submitReportAction(formData:FormData){const parsed=reportSchema.safeParse(Object.fromEntries(formData));if(!parsed.success)redirect("/denunciar?erro=Revise+os+campos+obrigatórios");const expectedHost=new URL(getShortDomain()).hostname;let reported;try{reported=new URL(parsed.data.url)}catch{redirect("/denunciar?erro=Link+inválido")}if(reported.hostname!==expectedHost&&!reported.hostname.endsWith(`.${expectedHost}`))redirect("/denunciar?erro=Informe+um+link+do+Encurta.io");const requestHeaders=await headers();const visitor=hashVisitorIdentifier(requestHeaders.get("x-forwarded-for")?.split(",")[0]??"unknown",requestHeaders.get("user-agent")??"")??"anonymous";const now=Date.now(),entry=attempts.get(visitor);if(entry&&entry.reset>now&&entry.count>=5)redirect("/denunciar?erro=Limite+temporário+atingido.+Tente+mais+tarde");attempts.set(visitor,{count:entry&&entry.reset>now?entry.count+1:1,reset:now+600000});const db=getServiceClient();if(!db)redirect("/denunciar?erro=Serviço+temporariamente+indisponível");const dbReason=(["phishing","fraude","spam"].includes(parsed.data.reason)?parsed.data.reason:"outro");const context=[`Motivo informado: ${parsed.data.reason}`,parsed.data.name?`Nome: ${parsed.data.name}`:null,parsed.data.evidence?`Evidências/observações: ${parsed.data.evidence}`:null,parsed.data.description].filter(Boolean).join("\n");const{error}=await db.from("abuse_reports").insert({reported_url:reported.toString(),reason:dbReason,description:context,email:parsed.data.email||null});if(error)redirect("/denunciar?erro=Não+foi+possível+enviar+a+denúncia");redirect("/denunciar?enviado=1")}
